baseURL = "http://example.org/"
languageCode = "ja-jp"
contentDir = "posts"
disableKinds = ["RSS", "sitemap"]
publishDir = "docs"
title = "Coffee Break"
theme = "tale"

github = "mildc055ee"

[params]
    github = "https://github.com/mildc055ee"

