baseURL = "https://blog.mildcoffee.dev"
languageCode = "ja-jp"
disableKinds = ["RSS", "sitemap"]
publishDir = "docs"
title = "Coffee Break"
theme = "tale"
googleAnalytics = "G-NQY19F5D3C"

github = "mildc055ee"

[params]
    github = "https://github.com/mildc055ee"

